[project]
name = "pocketbase"
version = "0.1.1"
description = "PocketBase client SDK for python."
authors = ["Vithor Jaeger <vaphes@gmail.com>"]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = "pocketbase client sdk"

[project.urls]
"Homepage" = "https://github.com/vaphes/pocketbase"
"Bug Tracker" = "https://github.com/vaphes/pocketbase/issues"

[tool.poetry]
name = "pocketbase"
version = "0.1.0"
description = "PocketBase client SDK for python."
authors = ["Vithor Jaeger <vaphes@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.23.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {version = "^22.8.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
